export default {
  actualComic: {
    month: '',
    num: null,
    link: '',
    year: '',
    news: '',
    safe_title: '',
    transcript: '',
    img: '',
    title: '',
    day: '',
    rate: 0,
  },
  latestNum: 2471,
  reviewedsComics: {},
  keyWord: '',
  sortMode: 1,
  isLoading: false,
};
